// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BasePaint$Type } from "./BasePaint";
import { BasePaintRaffle$Type } from "./BasePaintRaffle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BasePaint"]: BasePaint$Type;
    ["BasePaintRaffle"]: BasePaintRaffle$Type;
    ["contracts/BasePaintRaffle.sol:BasePaint"]: BasePaint$Type;
    ["contracts/BasePaintRaffle.sol:BasePaintRaffle"]: BasePaintRaffle$Type;
  }
}
